export const data = {
  education_type: {
    id: "",
    name_en: "",
    name_ru: "",
    name_uz: "",
  },
  faculty: {
    id: "",
    name_en: "",
    name_ru: "",
    name_uz: "",
  },
  faculty_language: {
    id: "",
    name_en: "",
    name_ru: "",
    name_uz: "",
  },
  image_url: "",
  info_en: {
    address: "",
    deadline: "",
    description: "",
    document_info: "",
    exam_description: "",
    name: "",
    price_in_word: "",
    visiting_month: "",
  },
  info_ru: {
    address: "",
    deadline: "",
    description: "",
    document_info: "",
    exam_description: "",
    name: "",
    price_in_word: "",
    visiting_month: "",
  },
  info_uz: {
    address: "",
    deadline: "",
    description: "",
    document_info: "",
    exam_description: "",
    name: "",
    price_in_word: "",
    visiting_month: "",
  },
  name_cyrillic: "",
  price: 0,
};
