export const ADMIN_LOGIN = "admin123@gmail.com"
export const ADMIN_PASSWORD = "Admin123"
export const APPLICATION_LOGIN = "application123@gmail.com"
export const APPLICATION_PASSWORD = "Application123"
export const CALLCENTER_LOGIN = "callCentre123@gmail.com"
export const CALLCENTER_PASSWORD = "CallCentre123"